language: python

env:
 - TOXENV=py27-1.5.x 
 - TOXENV=py27-1.6.x 

install:
 - pip install tox flake8

before_script:
 - flake8 firestone

script:
 - tox

after_success:
 - pip install coveralls
 - coveralls
